In [1]:
import numpy as np

In [2]:
def symmetrize(x):
  if len(x) % 2 == 0:
    x = np.concatenate \
    ( ( x[:len(x)//2]
      , np.full(2, 0.5*x[len(x)//2])
      , x[-(len(x)//2)+1:] ) )
  return x

In [3]:
def kin(ll, n):
  x = np.roll(np.arange(-(n//2), -(n//2)+n), -(n//2))
  x = -0.5*(2*np.pi/ll*(x[:, None]+x[None, :]))**2
  return x

In [4]:
def pot(ll, v):
  V = np.fft.fft(v)/len(v)/ll;
  V = symmetrize(V)
  return np.diag(V)

In [5]:
def cou(c, d):
  x = np.roll \
  ( np.arange(-(len(d)//2), -(len(d)//2)+len(d), dtype=np.int64)
  , -(len(d)//2) )
  t = x[None,:] - x[:,None] # t = q - p
  t_valid = (t <= len(d)//2)
  t *= t_valid
  r = x[:,None,None] + t[None,:,:] # r = s + t
  r_valid = (np.abs(r) <= len(d)//2)
  r *= r_valid
  rv \
  = np.conj(c)[:,r]     * r_valid[None,   :,:,:] \
  * d[t][None,None,:,:] * t_valid[None,None,:,:] \
  * c[:,x][:,:,None,None]
  return rv

In [6]:
def exc(c, d):
  x = np.roll \
  ( np.arange(-(len(d)//2), -(len(d)//2)+len(d), dtype=np.int64)
  , -(len(d)//2) )
  s = x[None,:,None] + x[:,None,None] # s = p + t
  s_valid = (s <= len(d)//2)
  s *= s_valid
  r = x[None,None,:] - x[:,None,None] # r = q - t
  r_valid = (np.abs(r) <= len(d)//2)
  r *= r_valid
  rv \
  = np.conj(c)[:,r] * r_valid[None,:,:,:] \
  * d[x][None,:,None,None] \
  * c[:,s]          * s_valid[None,:,:,:]
  return rv

In [7]:
ll = 16
d = np.cos(2*np.pi/4*np.arange(4))
D = symmetrize(np.fft.fft(d))
D

array([-1.2246468e-16+0.0000000e+00j,  2.0000000e+00-2.4492936e-16j,
        6.1232340e-17+0.0000000e+00j,  6.1232340e-17+0.0000000e+00j,
        2.0000000e+00+2.4492936e-16j])

In [8]:
np.set_printoptions(precision=2, linewidth=200)

In [9]:
cou \
( np.array
  ( [ [1, 0    , 0, 0, 0    ]
    , [0, 0.707, 0, 0, 0.707] ] )
, D )

array([[[[-1.22e-16+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j],
         [ 0.00e+00+0.j, -1.22e-16+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j],
         [ 0.00e+00+0.j,  0.00e+00+0.j, -1.22e-16+0.j,  0.00e+00+0.j,  0.00e+00+0.j],
         [ 0.00e+00+0.j, -0.00e+00+0.j, -0.00e+00+0.j, -1.22e-16+0.j,  0.00e+00+0.j],
         [ 0.00e+00+0.j,  0.00e+00+0.j, -0.00e+00+0.j,  0.00e+00+0.j, -1.22e-16+0.j]],

        [[-0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j],
         [ 0.00e+00+0.j, -0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j],
         [ 0.00e+00+0.j,  0.00e+00+0.j, -0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j],
         [ 0.00e+00+0.j, -0.00e+00+0.j, -0.00e+00+0.j, -0.00e+00+0.j,  0.00e+00+0.j],
         [ 0.00e+00+0.j,  0.00e+00+0.j, -0.00e+00+0.j,  0.00e+00+0.j, -0.00e+00+0.j]],

        [[-0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j,  0.00e+00+0.j],
         [ 0.00e+00+0.j, -0.00e+00+0.j,  0.00e+00+

In [10]:
exc \
( np.array
  ( [ [1, 0    , 0, 0, 0    ]
    , [0, 0.707, 0, 0, 0.707] ] )
, D )

array([[[[-1.22e-16+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j],
         [-0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j],
         [-0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j],
         [-0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j],
         [-0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j, -0.00e+00+0.00e+00j]],

        [[ 0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j],
         [ 0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j],
         [ 0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j],
         [ 0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00