In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=3, linewidth=100)

In [3]:
eig_vec = np.array \
( [ [ 1, 0      , 0       ]
  , [ 0, 2**-0.5, 0       ]
  , [ 0, 2**-0.5, 0       ]
  , [ 0, 0      , 2**-0.5 ]
  , [ 0, 0      , 2**-0.5 ] ] )

In [4]:
eig_vec

array([[1.   , 0.   , 0.   ],
       [0.   , 0.707, 0.   ],
       [0.   , 0.707, 0.   ],
       [0.   , 0.   , 0.707],
       [0.   , 0.   , 0.707]])

In [5]:
basis_nwn = np.array \
( [ [  0,  0 ]
  , [ -1,  0 ]
  , [  1,  0 ]
  , [  0, -1 ]
  , [  0,  1 ] ] )

In [6]:
basis_nwn

array([[ 0,  0],
       [-1,  0],
       [ 1,  0],
       [ 0, -1],
       [ 0,  1]])

In [7]:
box_size = np.array([1, 1])

In [8]:
box_size

array([1, 1])

In [9]:
box_size.prod()

1

In [10]:
vext = np.zeros((4, 4), dtype=float)

In [11]:
vext

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
wf_rc = np.zeros((eig_vec.shape[1],) + vext.shape, dtype=np.complex128)

In [13]:
wf_rc

array([[[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]]])

In [14]:
wf_rc[(slice(None), ) + tuple(basis_nwn.T)] = (eig_vec/box_size.prod()).T

In [15]:
wf_rc

array([[[1.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
        [0.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
        [0.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
        [0.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j]],

       [[0.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
        [0.707+0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
        [0.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
        [0.707+0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j]],

       [[0.   +0.j, 0.707+0.j, 0.   +0.j, 0.707+0.j],
        [0.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
        [0.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j],
        [0.   +0.j, 0.   +0.j, 0.   +0.j, 0.   +0.j]]])

In [16]:
wf = np.fft.ifftn(wf_rc, norm='forward', axes=range(1,wf_rc.ndim))

In [17]:
wf

array([[[ 1.   +0.j,  1.   +0.j,  1.   +0.j,  1.   +0.j],
        [ 1.   +0.j,  1.   +0.j,  1.   +0.j,  1.   +0.j],
        [ 1.   +0.j,  1.   +0.j,  1.   +0.j,  1.   +0.j],
        [ 1.   +0.j,  1.   +0.j,  1.   +0.j,  1.   +0.j]],

       [[ 1.414+0.j,  1.414+0.j,  1.414+0.j,  1.414+0.j],
        [ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j],
        [-1.414+0.j, -1.414+0.j, -1.414+0.j, -1.414+0.j],
        [ 0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j]],

       [[ 1.414+0.j,  0.   +0.j, -1.414+0.j,  0.   +0.j],
        [ 1.414+0.j,  0.   +0.j, -1.414+0.j,  0.   +0.j],
        [ 1.414+0.j,  0.   +0.j, -1.414+0.j,  0.   +0.j],
        [ 1.414+0.j,  0.   +0.j, -1.414+0.j,  0.   +0.j]]])

In [18]:
elec_density_each = wf.real**2 + wf.imag**2

In [19]:
elec_density_each

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[2., 2., 2., 2.],
        [0., 0., 0., 0.],
        [2., 2., 2., 2.],
        [0., 0., 0., 0.]],

       [[2., 0., 2., 0.],
        [2., 0., 2., 0.],
        [2., 0., 2., 0.],
        [2., 0., 2., 0.]]])

In [20]:
elec_density = elec_density_each.sum(axis=0)

In [21]:
elec_density

array([[5., 3., 5., 3.],
       [3., 1., 3., 1.],
       [5., 3., 5., 3.],
       [3., 1., 3., 1.]])

In [22]:
elec_density_rc = np.fft.fftn(elec_density, norm='forward')

In [23]:
elec_density_rc

array([[3.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])