In [1]:
import numpy as np
import p02

In [2]:
np.set_printoptions(precision=2)

In [3]:
basis_nwn = np.arange(-1, 2)[:, None]

In [4]:
basis_nwn

array([[-1],
       [ 0],
       [ 1]])

In [5]:
box_size = np.array([16])

In [6]:
box_size

array([16])

In [7]:
phase = np.linspace(0, 3*np.pi/2, 4)

In [8]:
phase

array([0.  , 1.57, 3.14, 4.71])

In [9]:
vext = np.cos(phase)

In [10]:
vext

array([ 1.00e+00,  6.12e-17, -1.00e+00, -1.84e-16])

In [11]:
vext_rc = np.fft.fft(vext)

In [12]:
vext_rc

array([-1.22e-16+0.00e+00j,  2.00e+00-2.45e-16j,  1.22e-16+0.00e+00j,
        2.00e+00+2.45e-16j])

In [13]:
vext_rc *= box_size.prod()

In [14]:
vext_rc

array([-1.96e-15+0.00e+00j,  3.20e+01-3.92e-15j,  1.96e-15+0.00e+00j,
        3.20e+01+3.92e-15j])

In [15]:
p02.symmetrize(vext_rc)

array([-1.96e-15+0.00e+00j,  3.20e+01-3.92e-15j,  9.80e-16+0.00e+00j,
        3.20e+01+3.92e-15j])

In [16]:
basis_nwn_cart = p02.f_basis_nwn_cart(basis_nwn)

In [17]:
basis_nwn_cart

array([[ 0,  0, -1, -1],
       [ 0,  1, -1,  0],
       [ 0,  2, -1,  1],
       [ 1,  0,  0, -1],
       [ 1,  1,  0,  0],
       [ 1,  2,  0,  1],
       [ 2,  0,  1, -1],
       [ 2,  1,  1,  0],
       [ 2,  2,  1,  1]])

In [18]:
vext_nwn = p02.f_vext_nwn(basis_nwn_cart, vext_rc)

In [19]:
vext_nwn

array([[ 0,  0,  0],
       [ 0,  1, -1],
       [ 0,  2, -2],
       [ 1,  0,  1],
       [ 1,  1,  0],
       [ 1,  2, -1],
       [ 2,  0,  2],
       [ 2,  1,  1],
       [ 2,  2,  0]])

In [20]:
vext_mat = p02.f_vext_mat(basis_nwn, vext_rc, vext_nwn)

In [21]:
vext_mat

array([[-1.96e-15+0.00e+00j,  3.20e+01+3.92e-15j,  9.80e-16+0.00e+00j],
       [ 3.20e+01-3.92e-15j, -1.96e-15+0.00e+00j,  3.20e+01+3.92e-15j],
       [ 9.80e-16+0.00e+00j,  3.20e+01-3.92e-15j, -1.96e-15+0.00e+00j]])

In [22]:
vext_nwn

array([[ 0,  0,  0],
       [ 0,  1, -1],
       [ 0,  2, -2],
       [ 1,  0,  1],
       [ 1,  1,  0],
       [ 1,  2, -1],
       [ 2,  0,  2],
       [ 2,  1,  1],
       [ 2,  2,  0]])

In [23]:
kin_mat = p02.f_kin_mat(basis_nwn, box_size)

In [24]:
kin_mat

array([[-0.  , -0.08, -0.31],
       [-0.08, -0.  , -0.08],
       [-0.31, -0.08, -0.  ]])

In [25]:
lhs = kin_mat + vext_mat

In [26]:
lhs

array([[-1.96e-15+0.00e+00j,  3.19e+01+3.92e-15j, -3.08e-01+0.00e+00j],
       [ 3.19e+01-3.92e-15j, -1.96e-15+0.00e+00j,  3.19e+01+3.92e-15j],
       [-3.08e-01+0.00e+00j,  3.19e+01-3.92e-15j, -1.96e-15+0.00e+00j]])

In [27]:
e, v = np.linalg.eigh(lhs)

In [28]:
e

array([-45.3 ,   0.31,  44.99])

In [29]:
v

array([[ 5.01e-01+0.00e+00j,  7.07e-01-0.00e+00j,  4.99e-01+0.00e+00j],
       [-7.06e-01+8.55e-17j,  1.89e-16+1.68e-18j,  7.08e-01-8.82e-17j],
       [ 5.01e-01-1.21e-16j, -7.07e-01+1.74e-16j,  4.99e-01-1.24e-16j]])

In [30]:
w1 = np.zeros(vext.shape[0], dtype=np.complex128)

In [31]:
w1

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [32]:
tuple(basis_nwn.T)

(array([-1,  0,  1]),)

In [33]:
w1[tuple(basis_nwn.T)] = v[:,0]

In [34]:
w1

array([-0.71+8.55e-17j,  0.5 -1.21e-16j,  0.  +0.00e+00j,  0.5 +0.00e+00j])

In [35]:
w = np.zeros((basis_nwn.shape[0], vext.shape[0]), dtype=np.complex128)

In [36]:
w[(slice(None), ) + tuple(basis_nwn.T)] = v.T

In [37]:
w

array([[-7.06e-01+8.55e-17j,  5.01e-01-1.21e-16j,  0.00e+00+0.00e+00j,
         5.01e-01+0.00e+00j],
       [ 1.89e-16+1.68e-18j, -7.07e-01+1.74e-16j,  0.00e+00+0.00e+00j,
         7.07e-01-0.00e+00j],
       [ 7.08e-01-8.82e-17j,  4.99e-01-1.24e-16j,  0.00e+00+0.00e+00j,
         4.99e-01+0.00e+00j]])

In [38]:
w_re = np.fft.ifft(w)

In [39]:
w_re

array([[ 7.40e-02-8.96e-18j, -1.76e-01+4.91e-17j, -4.27e-01+5.17e-17j,
        -1.76e-01-6.38e-18j],
       [ 1.03e-16+4.38e-17j,  3.86e-18-3.54e-01j, -8.24e-18-4.30e-17j,
         9.07e-17+3.54e-01j],
       [ 4.27e-01-5.31e-17j,  1.77e-01+1.17e-16j, -7.25e-02+9.02e-18j,
         1.77e-01-1.61e-16j]])

In [40]:
np.abs(w_re)

array([[7.40e-02, 1.76e-01, 4.27e-01, 1.76e-01],
       [1.12e-16, 3.54e-01, 4.38e-17, 3.54e-01],
       [4.27e-01, 1.77e-01, 7.25e-02, 1.77e-01]])