In [1]:
import numpy as np
import p02

/home/tyama/miniconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
d0 = p02.dist2([4], np.zeros(4))

In [3]:
d0

array([2.25, 0.25, 0.25, 2.25])

In [4]:
d = np.roll(d0, -(len(d0)//2))

In [5]:
d

array([0.25, 2.25, 2.25, 0.25])

In [6]:
D = np.fft.fftn(d, norm='forward')

In [7]:
D

array([ 1.25+0.j , -0.5 -0.5j,  0.  +0.j , -0.5 +0.5j])

In [8]:
Ds = p02.symmetrize4move(D)

In [9]:
Ds

array([ 1.25+0.j , -0.5 -0.5j,  0.  +0.j ,  0.  +0.j , -0.5 +0.5j])

In [10]:
Dss = p02.slide_half_grid(Ds)

[ 0.        +0.j -0.78539816+0.j -1.57079633+0.j  1.57079633+0.j
  0.78539816+0.j]


In [11]:
Dss

array([ 1.25      +0.00000000e+00j, -0.70710678-5.55111512e-17j,
        0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
       -0.70710678+5.55111512e-17j])

In [12]:
Dsso = p02.oversample_rc(Dss, [0])

In [13]:
Dsso

array([ 1.25      +0.00000000e+00j, -0.70710678-5.55111512e-17j,
        0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
        0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
        0.        +0.00000000e+00j, -0.70710678+5.55111512e-17j])

In [14]:
do = np.fft.ifftn(Dsso, norm='forward')

In [15]:
do

array([-0.16421356+0.j,  0.25      +0.j,  1.25      +0.j,  2.25      +0.j,
        2.66421356+0.j,  2.25      +0.j,  1.25      +0.j,  0.25      +0.j])