In [1]:
import numpy as np
import p02

In [2]:
np.set_printoptions(precision=2, linewidth=200)

In [3]:
basis_nwn = np.arange(-7, 8)[:, None]

In [4]:
basis_nwn

array([[-7],
       [-6],
       [-5],
       [-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7]])

In [5]:
box_size = np.array([2*np.pi])

In [6]:
box_size

array([6.28])

In [7]:
vext = np.full(32, 100, dtype=float)

In [8]:
vext[np.arange(-4, 4)] = 0

In [9]:
vext

array([  0.,   0.,   0.,   0., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,   0.,   0.,   0.,   0.])

In [10]:
vext_rc = np.fft.fft(vext, norm="forward")

In [11]:
vext_rc

array([ 75.  +0.j  , -22.44-2.21j, -15.71-3.12j,  -7.28-2.21j,   0.  +0.j  ,   4.13+2.21j,   4.68+3.12j,   2.69+2.21j,   0.  +0.j  ,  -1.81-2.21j,  -2.09-3.12j,  -1.18-2.21j,   0.  +0.j  ,
         0.67+2.21j,   0.62+3.12j,   0.22+2.21j,   0.  +0.j  ,   0.22-2.21j,   0.62-3.12j,   0.67-2.21j,   0.  +0.j  ,  -1.18+2.21j,  -2.09+3.12j,  -1.81+2.21j,   0.  +0.j  ,   2.69-2.21j,
         4.68-3.12j,   4.13-2.21j,   0.  +0.j  ,  -7.28+2.21j, -15.71+3.12j, -22.44+2.21j])

In [12]:
vext_rc *= box_size.prod()

In [13]:
vext_rc

array([ 471.24 +0.j  , -140.97-13.88j,  -98.71-19.63j,  -45.77-13.88j,    0.   +0.j  ,   25.98+13.88j,   29.39+19.63j,   16.92+13.88j,    0.   +0.j  ,  -11.39-13.88j,  -13.12-19.63j,   -7.42-13.88j,
          0.   +0.j  ,    4.21+13.88j,    3.91+19.63j,    1.37+13.88j,    0.   +0.j  ,    1.37-13.88j,    3.91-19.63j,    4.21-13.88j,    0.   +0.j  ,   -7.42+13.88j,  -13.12+19.63j,  -11.39+13.88j,
          0.   +0.j  ,   16.92-13.88j,   29.39-19.63j,   25.98-13.88j,    0.   +0.j  ,  -45.77+13.88j,  -98.71+19.63j, -140.97+13.88j])

In [14]:
p02.symmetrize(vext_rc)

array([ 471.24 +0.j  , -140.97-13.88j,  -98.71-19.63j,  -45.77-13.88j,    0.   +0.j  ,   25.98+13.88j,   29.39+19.63j,   16.92+13.88j,    0.   +0.j  ,  -11.39-13.88j,  -13.12-19.63j,   -7.42-13.88j,
          0.   +0.j  ,    4.21+13.88j,    3.91+19.63j,    1.37+13.88j,    0.   +0.j  ,    1.37-13.88j,    3.91-19.63j,    4.21-13.88j,    0.   +0.j  ,   -7.42+13.88j,  -13.12+19.63j,  -11.39+13.88j,
          0.   +0.j  ,   16.92-13.88j,   29.39-19.63j,   25.98-13.88j,    0.   +0.j  ,  -45.77+13.88j,  -98.71+19.63j, -140.97+13.88j])

In [15]:
basis_nwn_cart = p02.f_basis_nwn_cart(basis_nwn)

In [16]:
basis_nwn_cart

array([[ 0,  0, -7, -7],
       [ 0,  1, -7, -6],
       [ 0,  2, -7, -5],
       [ 0,  3, -7, -4],
       [ 0,  4, -7, -3],
       [ 0,  5, -7, -2],
       [ 0,  6, -7, -1],
       [ 0,  7, -7,  0],
       [ 0,  8, -7,  1],
       [ 0,  9, -7,  2],
       [ 0, 10, -7,  3],
       [ 0, 11, -7,  4],
       [ 0, 12, -7,  5],
       [ 0, 13, -7,  6],
       [ 0, 14, -7,  7],
       [ 1,  0, -6, -7],
       [ 1,  1, -6, -6],
       [ 1,  2, -6, -5],
       [ 1,  3, -6, -4],
       [ 1,  4, -6, -3],
       [ 1,  5, -6, -2],
       [ 1,  6, -6, -1],
       [ 1,  7, -6,  0],
       [ 1,  8, -6,  1],
       [ 1,  9, -6,  2],
       [ 1, 10, -6,  3],
       [ 1, 11, -6,  4],
       [ 1, 12, -6,  5],
       [ 1, 13, -6,  6],
       [ 1, 14, -6,  7],
       [ 2,  0, -5, -7],
       [ 2,  1, -5, -6],
       [ 2,  2, -5, -5],
       [ 2,  3, -5, -4],
       [ 2,  4, -5, -3],
       [ 2,  5, -5, -2],
       [ 2,  6, -5, -1],
       [ 2,  7, -5,  0],
       [ 2,  8, -5,  1],
       [ 2,  9, -5,  2],


In [17]:
vext_nwn = p02.f_vext_nwn(basis_nwn_cart, vext_rc)

In [18]:
vext_nwn

array([[  0,   0,   0],
       [  0,   1,  -1],
       [  0,   2,  -2],
       [  0,   3,  -3],
       [  0,   4,  -4],
       [  0,   5,  -5],
       [  0,   6,  -6],
       [  0,   7,  -7],
       [  0,   8,  -8],
       [  0,   9,  -9],
       [  0,  10, -10],
       [  0,  11, -11],
       [  0,  12, -12],
       [  0,  13, -13],
       [  0,  14, -14],
       [  1,   0,   1],
       [  1,   1,   0],
       [  1,   2,  -1],
       [  1,   3,  -2],
       [  1,   4,  -3],
       [  1,   5,  -4],
       [  1,   6,  -5],
       [  1,   7,  -6],
       [  1,   8,  -7],
       [  1,   9,  -8],
       [  1,  10,  -9],
       [  1,  11, -10],
       [  1,  12, -11],
       [  1,  13, -12],
       [  1,  14, -13],
       [  2,   0,   2],
       [  2,   1,   1],
       [  2,   2,   0],
       [  2,   3,  -1],
       [  2,   4,  -2],
       [  2,   5,  -3],
       [  2,   6,  -4],
       [  2,   7,  -5],
       [  2,   8,  -6],
       [  2,   9,  -7],
       [  2,  10,  -8],
       [  2,  11

In [19]:
vext_mat = p02.f_vext_mat(basis_nwn, vext_rc, vext_nwn)

In [20]:
vext_mat

array([[ 471.24 +0.j  , -140.97+13.88j,  -98.71+19.63j,  -45.77+13.88j,    0.   +0.j  ,   25.98-13.88j,   29.39-19.63j,   16.92-13.88j,    0.   +0.j  ,  -11.39+13.88j,  -13.12+19.63j,
          -7.42+13.88j,    0.   +0.j  ,    4.21-13.88j,    3.91-19.63j],
       [-140.97-13.88j,  471.24 +0.j  , -140.97+13.88j,  -98.71+19.63j,  -45.77+13.88j,    0.   +0.j  ,   25.98-13.88j,   29.39-19.63j,   16.92-13.88j,    0.   +0.j  ,  -11.39+13.88j,
         -13.12+19.63j,   -7.42+13.88j,    0.   +0.j  ,    4.21-13.88j],
       [ -98.71-19.63j, -140.97-13.88j,  471.24 +0.j  , -140.97+13.88j,  -98.71+19.63j,  -45.77+13.88j,    0.   +0.j  ,   25.98-13.88j,   29.39-19.63j,   16.92-13.88j,    0.   +0.j  ,
         -11.39+13.88j,  -13.12+19.63j,   -7.42+13.88j,    0.   +0.j  ],
       [ -45.77-13.88j,  -98.71-19.63j, -140.97-13.88j,  471.24 +0.j  , -140.97+13.88j,  -98.71+19.63j,  -45.77+13.88j,    0.   +0.j  ,   25.98-13.88j,   29.39-19.63j,   16.92-13.88j,
           0.   +0.j  ,  -11.39+13.88j,  -13.

In [21]:
kin_mat = p02.f_kin_mat(basis_nwn, box_size)

In [22]:
kin_mat

array([[24.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , 18. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , 12.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  8. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  4.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  2. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  2. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0

In [23]:
lhs = kin_mat + vext_mat

In [24]:
lhs

array([[ 495.74 +0.j  , -140.97+13.88j,  -98.71+19.63j,  -45.77+13.88j,    0.   +0.j  ,   25.98-13.88j,   29.39-19.63j,   16.92-13.88j,    0.   +0.j  ,  -11.39+13.88j,  -13.12+19.63j,
          -7.42+13.88j,    0.   +0.j  ,    4.21-13.88j,    3.91-19.63j],
       [-140.97-13.88j,  489.24 +0.j  , -140.97+13.88j,  -98.71+19.63j,  -45.77+13.88j,    0.   +0.j  ,   25.98-13.88j,   29.39-19.63j,   16.92-13.88j,    0.   +0.j  ,  -11.39+13.88j,
         -13.12+19.63j,   -7.42+13.88j,    0.   +0.j  ,    4.21-13.88j],
       [ -98.71-19.63j, -140.97-13.88j,  483.74 +0.j  , -140.97+13.88j,  -98.71+19.63j,  -45.77+13.88j,    0.   +0.j  ,   25.98-13.88j,   29.39-19.63j,   16.92-13.88j,    0.   +0.j  ,
         -11.39+13.88j,  -13.12+19.63j,   -7.42+13.88j,    0.   +0.j  ],
       [ -45.77-13.88j,  -98.71-19.63j, -140.97-13.88j,  479.24 +0.j  , -140.97+13.88j,  -98.71+19.63j,  -45.77+13.88j,    0.   +0.j  ,   25.98-13.88j,   29.39-19.63j,   16.92-13.88j,
           0.   +0.j  ,  -11.39+13.88j,  -13.

In [25]:
e, v = np.linalg.eigh(lhs)

In [26]:
e

array([  2.12,   8.41,  44.36, 249.15, 545.16, 628.54, 628.87, 630.35, 630.75, 633.98, 634.21, 639.45, 639.48, 646.73, 647.01])

In [27]:
(e/e[0])**0.5

array([ 1.  ,  1.99,  4.57, 10.84, 16.03, 17.21, 17.22, 17.24, 17.24, 17.29, 17.29, 17.36, 17.36, 17.46, 17.47])

In [28]:
v

array([[-1.21e-03+0.00e+00j,  7.94e-02-0.00e+00j,  2.48e-01+0.00e+00j, -4.49e-01+0.00e+00j,  5.27e-01+0.00e+00j, -1.40e-02+0.00e+00j,  9.85e-02+0.00e+00j,  4.42e-02+0.00e+00j,  1.55e-01+0.00e+00j,
        -8.25e-02+0.00e+00j, -1.89e-01+0.00e+00j, -2.36e-01+0.00e+00j,  1.47e-01+0.00e+00j,  4.09e-01+0.00e+00j,  3.61e-01+0.00e+00j],
       [-2.94e-02-2.90e-03j,  1.74e-01+1.72e-02j,  3.49e-01+3.43e-02j, -3.83e-01-3.78e-02j,  2.05e-01+2.02e-02j, -4.36e-03-4.30e-04j,  3.34e-02+3.29e-03j,  1.39e-02+1.37e-03j,  5.11e-02+5.03e-03j,
        -2.74e-02-2.69e-03j, -6.00e-02-5.91e-03j, -7.45e-02-7.33e-03j,  5.89e-02+5.80e-03j, -5.52e-01-5.44e-02j, -5.71e-01-5.62e-02j],
       [-8.36e-02-1.66e-02j,  2.72e-01+5.41e-02j,  3.69e-01+7.34e-02j, -2.08e-01-4.13e-02j, -9.59e-02-1.91e-02j,  9.76e-03+1.94e-03j, -3.39e-02-6.73e-03j, -3.37e-02-6.71e-03j, -6.24e-02-1.24e-02j,
         8.27e-02+1.65e-02j,  1.11e-01+2.21e-02j,  5.73e-01+1.14e-01j, -5.50e-01-1.09e-01j,  1.33e-01+2.64e-02j,  1.33e-01+2.65e-02j],
    

In [29]:
w1 = np.zeros(vext.shape[0], dtype=np.complex128)

In [30]:
w1

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [31]:
tuple(basis_nwn.T)

(array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7]),)

In [32]:
w1[tuple(basis_nwn.T)] = v[:,0]

In [33]:
w1

array([-3.41e-01-0.28j, -2.95e-01-0.3j , -2.23e-01-0.27j, -1.45e-01-0.22j, -7.84e-02-0.15j, -3.26e-02-0.08j, -8.58e-03-0.03j, -2.36e-04-0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,
        0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  ,
        0.00e+00+0.j  ,  0.00e+00+0.j  ,  0.00e+00+0.j  , -1.21e-03+0.j  , -2.94e-02-0.j  , -8.36e-02-0.02j, -1.59e-01-0.05j, -2.42e-01-0.1j , -3.11e-01-0.17j, -3.47e-01-0.23j])

In [34]:
w = np.zeros((basis_nwn.shape[0], vext.shape[0]), dtype=np.complex128)

In [35]:
w[(slice(None), ) + tuple(basis_nwn.T)] = v.T

In [36]:
w

array([[-3.41e-01-2.80e-01j, -2.95e-01-2.95e-01j, -2.23e-01-2.72e-01j, -1.45e-01-2.17e-01j, -7.84e-02-1.47e-01j, -3.26e-02-7.87e-02j, -8.58e-03-2.83e-02j, -2.36e-04-1.19e-03j,  0.00e+00+0.00e+00j,
         0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,
         0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j, -1.21e-03+0.00e+00j, -2.94e-02-2.90e-03j,
        -8.36e-02-1.66e-02j, -1.59e-01-4.83e-02j, -2.42e-01-1.00e-01j, -3.11e-01-1.66e-01j, -3.47e-01-2.32e-01j],
       [ 1.96e-16+2.56e-16j, -1.24e-01-1.24e-01j, -1.95e-01-2.38e-01j, -2.05e-01-3.07e-01j, -1.66e-01-3.11e-01j, -1.06e-01-2.56e-01j, -5.08e-02-1.68e-01j, -1.55e-02-7.78e-02j,  0.00e+00+0.00e+00j,
         0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e

In [37]:
w_re = np.fft.ifft(w)

In [38]:
w_re

array([[-7.18e-02-5.89e-02j, -5.53e-02-4.54e-02j, -3.14e-02-2.58e-02j, -1.15e-02-9.41e-03j, -1.23e-03-1.01e-03j,  9.04e-04+7.42e-04j,  6.93e-07+5.69e-07j, -4.20e-04-3.45e-04j,  5.62e-06+4.62e-06j,
         2.67e-04+2.19e-04j,  2.88e-05+2.37e-05j, -1.96e-04-1.61e-04j, -6.09e-05-5.00e-05j,  1.52e-04+1.25e-04j,  9.00e-05+7.38e-05j, -1.19e-04-9.76e-05j, -1.19e-04-9.76e-05j,  9.00e-05+7.38e-05j,
         1.52e-04+1.25e-04j, -6.09e-05-5.00e-05j, -1.96e-04-1.61e-04j,  2.88e-05+2.37e-05j,  2.67e-04+2.19e-04j,  5.62e-06+4.62e-06j, -4.20e-04-3.45e-04j,  6.93e-07+5.69e-07j,  9.04e-04+7.42e-04j,
        -1.23e-03-1.01e-03j, -1.15e-02-9.41e-03j, -3.14e-02-2.58e-02j, -5.53e-02-4.54e-02j, -7.18e-02-5.89e-02j],
       [ 2.37e-02-2.89e-02j,  5.36e-02-6.53e-02j,  4.83e-02-5.89e-02j,  2.25e-02-2.75e-02j,  2.28e-03-2.78e-03j, -2.21e-03+2.69e-03j,  6.11e-04-7.44e-04j,  1.09e-03-1.32e-03j, -6.85e-04+8.35e-04j,
        -7.27e-04+8.86e-04j,  6.25e-04-7.62e-04j,  5.85e-04-7.13e-04j, -5.69e-04+6.94e-04j, -5.30e

In [39]:
np.abs(w_re)

array([[9.29e-02, 7.15e-02, 4.07e-02, 1.48e-02, 1.59e-03, 1.17e-03, 8.97e-07, 5.43e-04, 7.28e-06, 3.46e-04, 3.73e-05, 2.53e-04, 7.88e-05, 1.96e-04, 1.16e-04, 1.54e-04, 1.54e-04, 1.16e-04, 1.96e-04,
        7.88e-05, 2.53e-04, 3.73e-05, 3.46e-04, 7.28e-06, 5.43e-04, 8.97e-07, 1.17e-03, 1.59e-03, 1.48e-02, 4.07e-02, 7.15e-02, 9.29e-02],
       [3.74e-02, 8.44e-02, 7.62e-02, 3.55e-02, 3.60e-03, 3.48e-03, 9.62e-04, 1.71e-03, 1.08e-03, 1.15e-03, 9.86e-04, 9.23e-04, 8.98e-04, 8.35e-04, 8.40e-04, 8.16e-04, 8.16e-04, 8.40e-04, 8.35e-04,
        8.98e-04, 9.23e-04, 9.86e-04, 1.15e-03, 1.08e-03, 1.71e-03, 9.62e-04, 3.48e-03, 3.60e-03, 3.55e-02, 7.62e-02, 8.44e-02, 3.74e-02],
       [5.79e-02, 1.50e-02, 7.86e-02, 7.12e-02, 1.91e-02, 1.27e-02, 5.01e-03, 8.64e-03, 3.44e-03, 6.69e-03, 3.23e-03, 5.53e-03, 3.39e-03, 4.74e-03, 3.71e-03, 4.16e-03, 4.16e-03, 3.71e-03, 4.74e-03,
        3.39e-03, 5.53e-03, 3.23e-03, 6.69e-03, 3.44e-03, 8.64e-03, 5.01e-03, 1.27e-02, 1.91e-02, 7.12e-02, 7.86e-02, 1.50e-02, 