In [37]:
import numpy as np
import p02

In [38]:
np.set_printoptions(precision=2, linewidth=200)

In [39]:
basis_nwn = np.arange(-4, 5)[:, None]

In [40]:
basis_nwn

array([[-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [41]:
box_size = np.array([2*np.pi])

In [42]:
box_size

array([6.28])

In [43]:
vext = np.full(16, 20, dtype=float)

In [44]:
vext[0:7] = 0

In [45]:
vext

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0., 20., 20., 20., 20., 20., 20., 20., 20., 20.])

In [46]:
vext_rc = np.fft.fft(vext, norm="forward")

In [47]:
vext_rc

array([11.25+0.j  , -2.4 +5.81j,  0.88+0.88j, -1.73+0.72j,  0.  +1.25j, -0.77-0.32j, -0.88+0.88j, -0.1 -0.23j, -1.25+0.j  , -0.1 +0.23j, -0.88-0.88j, -0.77+0.32j,  0.  -1.25j, -1.73-0.72j,
        0.88-0.88j, -2.4 -5.81j])

In [48]:
p02.symmetrize(vext_rc)

array([11.25+0.j  , -2.4 +5.81j,  0.88+0.88j, -1.73+0.72j,  0.  +1.25j, -0.77-0.32j, -0.88+0.88j, -0.1 -0.23j, -0.62+0.j  , -0.1 +0.23j, -0.88-0.88j, -0.77+0.32j,  0.  -1.25j, -1.73-0.72j,
        0.88-0.88j, -2.4 -5.81j])

In [49]:
basis_nwn_cart = p02.f_basis_nwn_cart(basis_nwn)

In [50]:
basis_nwn_cart

array([[ 0,  0, -4, -4],
       [ 0,  1, -4, -3],
       [ 0,  2, -4, -2],
       [ 0,  3, -4, -1],
       [ 0,  4, -4,  0],
       [ 0,  5, -4,  1],
       [ 0,  6, -4,  2],
       [ 0,  7, -4,  3],
       [ 0,  8, -4,  4],
       [ 1,  0, -3, -4],
       [ 1,  1, -3, -3],
       [ 1,  2, -3, -2],
       [ 1,  3, -3, -1],
       [ 1,  4, -3,  0],
       [ 1,  5, -3,  1],
       [ 1,  6, -3,  2],
       [ 1,  7, -3,  3],
       [ 1,  8, -3,  4],
       [ 2,  0, -2, -4],
       [ 2,  1, -2, -3],
       [ 2,  2, -2, -2],
       [ 2,  3, -2, -1],
       [ 2,  4, -2,  0],
       [ 2,  5, -2,  1],
       [ 2,  6, -2,  2],
       [ 2,  7, -2,  3],
       [ 2,  8, -2,  4],
       [ 3,  0, -1, -4],
       [ 3,  1, -1, -3],
       [ 3,  2, -1, -2],
       [ 3,  3, -1, -1],
       [ 3,  4, -1,  0],
       [ 3,  5, -1,  1],
       [ 3,  6, -1,  2],
       [ 3,  7, -1,  3],
       [ 3,  8, -1,  4],
       [ 4,  0,  0, -4],
       [ 4,  1,  0, -3],
       [ 4,  2,  0, -2],
       [ 4,  3,  0, -1],


In [51]:
vext_nwn = p02.f_vext_nwn(basis_nwn_cart, vext_rc)

In [52]:
vext_nwn

array([[ 0,  0,  0],
       [ 0,  1, -1],
       [ 0,  2, -2],
       [ 0,  3, -3],
       [ 0,  4, -4],
       [ 0,  5, -5],
       [ 0,  6, -6],
       [ 0,  7, -7],
       [ 0,  8, -8],
       [ 1,  0,  1],
       [ 1,  1,  0],
       [ 1,  2, -1],
       [ 1,  3, -2],
       [ 1,  4, -3],
       [ 1,  5, -4],
       [ 1,  6, -5],
       [ 1,  7, -6],
       [ 1,  8, -7],
       [ 2,  0,  2],
       [ 2,  1,  1],
       [ 2,  2,  0],
       [ 2,  3, -1],
       [ 2,  4, -2],
       [ 2,  5, -3],
       [ 2,  6, -4],
       [ 2,  7, -5],
       [ 2,  8, -6],
       [ 3,  0,  3],
       [ 3,  1,  2],
       [ 3,  2,  1],
       [ 3,  3,  0],
       [ 3,  4, -1],
       [ 3,  5, -2],
       [ 3,  6, -3],
       [ 3,  7, -4],
       [ 3,  8, -5],
       [ 4,  0,  4],
       [ 4,  1,  3],
       [ 4,  2,  2],
       [ 4,  3,  1],
       [ 4,  4,  0],
       [ 4,  5, -1],
       [ 4,  6, -2],
       [ 4,  7, -3],
       [ 4,  8, -4],
       [ 5,  0,  5],
       [ 5,  1,  4],
       [ 5,  

In [53]:
vext_mat = p02.f_vext_mat(basis_nwn, vext_rc, vext_nwn)

In [54]:
vext_mat

array([[11.25+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j, -0.77+0.32j, -0.88-0.88j, -0.1 +0.23j, -0.62+0.j  ],
       [-2.4 +5.81j, 11.25+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j, -0.77+0.32j, -0.88-0.88j, -0.1 +0.23j],
       [ 0.88+0.88j, -2.4 +5.81j, 11.25+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j, -0.77+0.32j, -0.88-0.88j],
       [-1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 11.25+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j, -0.77+0.32j],
       [ 0.  +1.25j, -1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 11.25+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j],
       [-0.77-0.32j,  0.  +1.25j, -1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 11.25+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j],
       [-0.88+0.88j, -0.77-0.32j,  0.  +1.25j, -1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 11.25+0.j  , -2.4 -5.81j,  0.88-0.88j],
       [-0.1 -0.23j, -0.88+0.88j, -0.77-0.32j,  0.  +1.25j, -1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 11.25+0.j  , -2.4 -

In [55]:
kin_mat = p02.f_kin_mat(basis_nwn, box_size)

In [56]:
kin_mat

array([[8. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 4.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 2. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 2. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 4.5, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 8. ]])

In [57]:
lhs = kin_mat + vext_mat

In [58]:
lhs

array([[19.25+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j, -0.77+0.32j, -0.88-0.88j, -0.1 +0.23j, -0.62+0.j  ],
       [-2.4 +5.81j, 15.75+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j, -0.77+0.32j, -0.88-0.88j, -0.1 +0.23j],
       [ 0.88+0.88j, -2.4 +5.81j, 13.25+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j, -0.77+0.32j, -0.88-0.88j],
       [-1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 11.75+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j, -0.77+0.32j],
       [ 0.  +1.25j, -1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 11.25+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j,  0.  -1.25j],
       [-0.77-0.32j,  0.  +1.25j, -1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 11.75+0.j  , -2.4 -5.81j,  0.88-0.88j, -1.73-0.72j],
       [-0.88+0.88j, -0.77-0.32j,  0.  +1.25j, -1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 13.25+0.j  , -2.4 -5.81j,  0.88-0.88j],
       [-0.1 -0.23j, -0.88+0.88j, -0.77-0.32j,  0.  +1.25j, -1.73+0.72j,  0.88+0.88j, -2.4 +5.81j, 15.75+0.j  , -2.4 -

In [59]:
e, v = np.linalg.eigh(lhs)

In [60]:
e

array([ 0.5 ,  2.09,  4.55, 11.41, 20.03, 21.13, 21.44, 24.41, 25.68])

In [61]:
v

array([[ 3.98e-02-0.00e+00j,  3.68e-02+0.00e+00j, -2.77e-01+0.00e+00j,  4.90e-01+0.00e+00j, -2.42e-01+0.00e+00j,  3.71e-01+0.00e+00j,  1.32e-01+0.00e+00j,  4.75e-01+0.00e+00j,  4.91e-01+0.00e+00j],
       [-1.42e-03+3.44e-03j,  1.03e-01-2.48e-01j, -1.88e-01+4.55e-01j,  1.62e-01-3.91e-01j, -4.59e-02+1.11e-01j,  5.90e-02-1.42e-01j,  5.32e-02-1.28e-01j, -1.79e-01+4.33e-01j, -1.83e-01+4.43e-01j],
       [ 1.48e-01+1.48e-01j, -3.51e-01-3.51e-01j,  2.78e-01+2.78e-01j,  1.60e-02+1.60e-02j, -7.76e-02-7.76e-02j,  3.45e-01+3.45e-01j,  3.46e-01+3.46e-01j, -1.60e-01-1.60e-01j, -8.26e-02-8.26e-02j],
       [ 4.61e-01-1.91e-01j, -3.92e-01+1.62e-01j,  8.01e-04-3.32e-04j,  2.63e-01-1.09e-01j, -3.66e-01+1.52e-01j, -2.83e-01+1.17e-01j, -4.37e-01+1.81e-01j, -3.90e-03+1.62e-03j, -1.15e-01+4.75e-02j],
       [ 7.54e-16-6.41e-01j, -5.74e-16-5.32e-16j,  6.47e-17+2.30e-01j, -2.27e-17+3.22e-16j, -1.66e-16-7.18e-01j,  8.09e-16-1.13e-01j, -2.77e-15-5.58e-15j,  3.45e-16-9.00e-02j, -2.71e-16-2.70e-16j],
       [-4

In [62]:
w1 = np.zeros(vext.shape[0], dtype=np.complex128)

In [63]:
w1

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [64]:
tuple(basis_nwn.T)

(array([-4, -3, -2, -1,  0,  1,  2,  3,  4]),)

In [65]:
w1[tuple(basis_nwn.T)] = v[:,0]

In [66]:
w1

array([ 7.54e-16-6.41e-01j, -4.61e-01-1.91e-01j, -1.48e-01+1.48e-01j,  1.42e-03+3.44e-03j, -3.98e-02-4.68e-17j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,
        0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  3.98e-02-0.00e+00j, -1.42e-03+3.44e-03j,  1.48e-01+1.48e-01j,  4.61e-01-1.91e-01j])

In [67]:
w = np.zeros((basis_nwn.shape[0], vext.shape[0]), dtype=np.complex128)

In [68]:
w[(slice(None), ) + tuple(basis_nwn.T)] = v.T

In [69]:
w

array([[ 7.54e-16-6.41e-01j, -4.61e-01-1.91e-01j, -1.48e-01+1.48e-01j,  1.42e-03+3.44e-03j, -3.98e-02-4.68e-17j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,
         0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  3.98e-02-0.00e+00j, -1.42e-03+3.44e-03j,  1.48e-01+1.48e-01j,  4.61e-01-1.91e-01j],
       [-5.74e-16-5.32e-16j, -3.92e-01-1.62e-01j, -3.51e-01+3.51e-01j,  1.03e-01+2.48e-01j,  3.68e-02+1.12e-16j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,
         0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  3.68e-02+0.00e+00j,  1.03e-01-2.48e-01j, -3.51e-01-3.51e-01j, -3.92e-01+1.62e-01j],
       [ 6.47e-17+2.30e-01j, -8.01e-04-3.32e-04j, -2.78e-01+2.78e-01j,  1.88e-01+4.55e-01j,  2.77e-01+6.01e-17j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,
         0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j,  0.00e+00+0.00e+00j, -2.77e-01+0.00e+00j, -1.88

In [70]:
w_re = np.fft.ifft(w)

In [71]:
w_re

array([[ 7.83e-17-4.50e-02j,  2.03e-16-8.88e-02j,  2.57e-16-1.16e-01j,  1.83e-16-1.24e-01j,  6.27e-17-1.16e-01j,  4.45e-18-8.88e-02j,  5.49e-18-4.50e-02j,  2.56e-18-8.88e-03j, -4.92e-18+1.93e-03j,
        -4.98e-18-1.22e-03j, -3.19e-18-7.11e-04j, -1.13e-17+1.64e-03j, -1.01e-17-7.11e-04j, -2.49e-18-1.22e-03j, -8.39e-18+1.93e-03j,  2.56e-18-8.88e-03j],
       [-7.54e-02-2.86e-16j, -1.23e-01-3.98e-16j, -9.98e-02-2.59e-16j, -1.21e-16+1.85e-17j,  9.98e-02+1.99e-16j,  1.23e-01+2.02e-16j,  7.54e-02+1.02e-16j,  1.94e-02+2.48e-17j, -3.21e-03+5.00e-18j,
        -8.69e-04+4.07e-18j,  2.81e-03+4.88e-18j,  1.38e-17-9.26e-18j, -2.81e-03-2.28e-17j,  8.69e-04-1.33e-17j,  3.21e-03-8.99e-18j, -1.94e-02-9.40e-17j],
       [-1.33e-17+1.06e-01j, -6.81e-17+9.24e-02j, -3.07e-17-4.40e-02j,  4.25e-17-1.31e-01j,  9.08e-17-4.40e-02j,  6.87e-17+9.24e-02j, -6.37e-18+1.06e-01j, -6.51e-17+2.89e-02j, -2.72e-17-7.70e-03j,
         6.38e-17+5.51e-03j,  8.04e-17+3.25e-03j,  8.58e-19-7.73e-03j, -8.96e-17+3.25e-03j, -6.32

In [72]:
np.abs(w_re)

array([[4.50e-02, 8.88e-02, 1.16e-01, 1.24e-01, 1.16e-01, 8.88e-02, 4.50e-02, 8.88e-03, 1.93e-03, 1.22e-03, 7.11e-04, 1.64e-03, 7.11e-04, 1.22e-03, 1.93e-03, 8.88e-03],
       [7.54e-02, 1.23e-01, 9.98e-02, 1.22e-16, 9.98e-02, 1.23e-01, 7.54e-02, 1.94e-02, 3.21e-03, 8.69e-04, 2.81e-03, 1.66e-17, 2.81e-03, 8.69e-04, 3.21e-03, 1.94e-02],
       [1.06e-01, 9.24e-02, 4.40e-02, 1.31e-01, 4.40e-02, 9.24e-02, 1.06e-01, 2.89e-02, 7.70e-03, 5.51e-03, 3.25e-03, 7.73e-03, 3.25e-03, 5.51e-03, 7.70e-03, 2.89e-02],
       [1.16e-01, 9.43e-03, 9.45e-02, 6.04e-17, 9.45e-02, 9.43e-03, 1.16e-01, 8.84e-02, 1.01e-02, 1.51e-02, 2.40e-02, 2.87e-17, 2.40e-02, 1.51e-02, 1.01e-02, 8.84e-02],
       [2.18e-02, 3.10e-02, 4.84e-03, 2.69e-02, 4.84e-03, 3.10e-02, 2.18e-02, 8.89e-02, 8.74e-02, 6.02e-02, 7.52e-02, 9.60e-02, 7.52e-02, 6.02e-02, 8.74e-02, 8.89e-02],
       [3.29e-02, 4.01e-02, 7.52e-03, 3.58e-02, 7.52e-03, 4.01e-02, 3.29e-02, 1.00e-01, 3.92e-02, 6.69e-02, 9.29e-02, 7.92e-02, 9.29e-02, 6.69e-02, 3.92e-0