In [1]:
import numpy as np
import p02

In [2]:
np.set_printoptions(precision=2, linewidth=200)

In [3]:
basis_nwn = np.arange(-255, 256)[:, None]

In [4]:
basis_nwn

array([[-255],
       [-254],
       [-253],
       [-252],
       [-251],
       [-250],
       [-249],
       [-248],
       [-247],
       [-246],
       [-245],
       [-244],
       [-243],
       [-242],
       [-241],
       [-240],
       [-239],
       [-238],
       [-237],
       [-236],
       [-235],
       [-234],
       [-233],
       [-232],
       [-231],
       [-230],
       [-229],
       [-228],
       [-227],
       [-226],
       [-225],
       [-224],
       [-223],
       [-222],
       [-221],
       [-220],
       [-219],
       [-218],
       [-217],
       [-216],
       [-215],
       [-214],
       [-213],
       [-212],
       [-211],
       [-210],
       [-209],
       [-208],
       [-207],
       [-206],
       [-205],
       [-204],
       [-203],
       [-202],
       [-201],
       [-200],
       [-199],
       [-198],
       [-197],
       [-196],
       [-195],
       [-194],
       [-193],
       [-192],
       [-191],
       [-190],
       [-1

In [5]:
box_size = np.array([2*np.pi])

In [6]:
box_size

array([6.28])

In [7]:
vext = np.full(512, 50, dtype=float)

In [8]:
vext[np.arange(-63,64)] = 0

In [9]:
vext

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
       50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
       50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
       50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50., 50.,
       50., 50.

In [10]:
vext_rc = np.fft.fft(vext, norm="forward")

In [11]:
vext_rc

array([ 3.76e+01+0.j, -1.12e+01+0.j, -7.96e+00+0.j, -3.82e+00+0.j, -9.77e-02+0.j,  2.18e+00+0.j,  2.65e+00+0.j,  1.68e+00+0.j,  9.77e-02+0.j, -1.18e+00+0.j, -1.59e+00+0.j, -1.09e+00+0.j,
       -9.77e-02+0.j,  7.95e-01+0.j,  1.13e+00+0.j,  8.17e-01+0.j,  9.77e-02+0.j, -5.91e-01+0.j, -8.81e-01+0.j, -6.59e-01+0.j, -9.77e-02+0.j,  4.64e-01+0.j,  7.19e-01+0.j,  5.55e-01+0.j,
        9.77e-02+0.j, -3.78e-01+0.j, -6.07e-01+0.j, -4.82e-01+0.j, -9.77e-02+0.j,  3.15e-01+0.j,  5.25e-01+0.j,  4.28e-01+0.j,  9.77e-02+0.j, -2.67e-01+0.j, -4.61e-01+0.j, -3.86e-01+0.j,
       -9.77e-02+0.j,  2.30e-01+0.j,  4.11e-01+0.j,  3.52e-01+0.j,  9.77e-02+0.j, -2.00e-01+0.j, -3.71e-01+0.j, -3.25e-01+0.j, -9.77e-02+0.j,  1.75e-01+0.j,  3.37e-01+0.j,  3.02e-01+0.j,
        9.77e-02+0.j, -1.54e-01+0.j, -3.08e-01+0.j, -2.82e-01+0.j, -9.77e-02+0.j,  1.36e-01+0.j,  2.84e-01+0.j,  2.66e-01+0.j,  9.77e-02+0.j, -1.20e-01+0.j, -2.63e-01+0.j, -2.51e-01+0.j,
       -9.77e-02+0.j,  1.07e-01+0.j,  2.44e-01+0.j,  2.39e-01+0.j

In [12]:
vext_rc *= box_size.prod()

In [13]:
vext_rc

array([ 2.36e+02+0.j, -7.03e+01+0.j, -5.00e+01+0.j, -2.40e+01+0.j, -6.14e-01+0.j,  1.37e+01+0.j,  1.67e+01+0.j,  1.05e+01+0.j,  6.14e-01+0.j, -7.41e+00+0.j, -9.99e+00+0.j, -6.85e+00+0.j,
       -6.14e-01+0.j,  4.99e+00+0.j,  7.13e+00+0.j,  5.13e+00+0.j,  6.14e-01+0.j, -3.71e+00+0.j, -5.53e+00+0.j, -4.14e+00+0.j, -6.14e-01+0.j,  2.91e+00+0.j,  4.52e+00+0.j,  3.49e+00+0.j,
        6.14e-01+0.j, -2.37e+00+0.j, -3.81e+00+0.j, -3.03e+00+0.j, -6.14e-01+0.j,  1.98e+00+0.j,  3.30e+00+0.j,  2.69e+00+0.j,  6.14e-01+0.j, -1.68e+00+0.j, -2.90e+00+0.j, -2.42e+00+0.j,
       -6.14e-01+0.j,  1.44e+00+0.j,  2.58e+00+0.j,  2.21e+00+0.j,  6.14e-01+0.j, -1.25e+00+0.j, -2.33e+00+0.j, -2.04e+00+0.j, -6.14e-01+0.j,  1.10e+00+0.j,  2.12e+00+0.j,  1.90e+00+0.j,
        6.14e-01+0.j, -9.65e-01+0.j, -1.94e+00+0.j, -1.77e+00+0.j, -6.14e-01+0.j,  8.53e-01+0.j,  1.78e+00+0.j,  1.67e+00+0.j,  6.14e-01+0.j, -7.56e-01+0.j, -1.65e+00+0.j, -1.58e+00+0.j,
       -6.14e-01+0.j,  6.71e-01+0.j,  1.53e+00+0.j,  1.50e+00+0.j

In [14]:
p02.symmetrize(vext_rc)

array([ 2.36e+02+0.j, -7.03e+01+0.j, -5.00e+01+0.j, -2.40e+01+0.j, -6.14e-01+0.j,  1.37e+01+0.j,  1.67e+01+0.j,  1.05e+01+0.j,  6.14e-01+0.j, -7.41e+00+0.j, -9.99e+00+0.j, -6.85e+00+0.j,
       -6.14e-01+0.j,  4.99e+00+0.j,  7.13e+00+0.j,  5.13e+00+0.j,  6.14e-01+0.j, -3.71e+00+0.j, -5.53e+00+0.j, -4.14e+00+0.j, -6.14e-01+0.j,  2.91e+00+0.j,  4.52e+00+0.j,  3.49e+00+0.j,
        6.14e-01+0.j, -2.37e+00+0.j, -3.81e+00+0.j, -3.03e+00+0.j, -6.14e-01+0.j,  1.98e+00+0.j,  3.30e+00+0.j,  2.69e+00+0.j,  6.14e-01+0.j, -1.68e+00+0.j, -2.90e+00+0.j, -2.42e+00+0.j,
       -6.14e-01+0.j,  1.44e+00+0.j,  2.58e+00+0.j,  2.21e+00+0.j,  6.14e-01+0.j, -1.25e+00+0.j, -2.33e+00+0.j, -2.04e+00+0.j, -6.14e-01+0.j,  1.10e+00+0.j,  2.12e+00+0.j,  1.90e+00+0.j,
        6.14e-01+0.j, -9.65e-01+0.j, -1.94e+00+0.j, -1.77e+00+0.j, -6.14e-01+0.j,  8.53e-01+0.j,  1.78e+00+0.j,  1.67e+00+0.j,  6.14e-01+0.j, -7.56e-01+0.j, -1.65e+00+0.j, -1.58e+00+0.j,
       -6.14e-01+0.j,  6.71e-01+0.j,  1.53e+00+0.j,  1.50e+00+0.j

In [15]:
basis_nwn_cart = p02.f_basis_nwn_cart(basis_nwn)

In [16]:
basis_nwn_cart

array([[   0,    0, -255, -255],
       [   0,    1, -255, -254],
       [   0,    2, -255, -253],
       ...,
       [ 510,  508,  255,  253],
       [ 510,  509,  255,  254],
       [ 510,  510,  255,  255]])

In [17]:
vext_nwn = p02.f_vext_nwn(basis_nwn_cart, vext_rc)

In [18]:
vext_nwn

array([[  0,   0,   0],
       [  0,   1,  -1],
       [  0,   2,  -2],
       ...,
       [510, 508,   2],
       [510, 509,   1],
       [510, 510,   0]])

In [19]:
vext_mat = p02.f_vext_mat(basis_nwn, vext_rc, vext_nwn)

In [20]:
vext_mat

array([[236.23+0.j, -70.28+0.j, -50.  +0.j, ...,   0.  +0.j,   0.  +0.j,   0.  +0.j],
       [-70.28+0.j, 236.23+0.j, -70.28+0.j, ...,   0.  +0.j,   0.  +0.j,   0.  +0.j],
       [-50.  +0.j, -70.28+0.j, 236.23+0.j, ...,   0.  +0.j,   0.  +0.j,   0.  +0.j],
       ...,
       [  0.  +0.j,   0.  +0.j,   0.  +0.j, ..., 236.23+0.j, -70.28+0.j, -50.  +0.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j, ..., -70.28+0.j, 236.23+0.j, -70.28+0.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j, ..., -50.  +0.j, -70.28+0.j, 236.23+0.j]])

In [21]:
kin_mat = p02.f_kin_mat(basis_nwn, box_size)

In [22]:
kin_mat

array([[32512.5,     0. ,     0. , ...,     0. ,     0. ,     0. ],
       [    0. , 32258. ,     0. , ...,     0. ,     0. ,     0. ],
       [    0. ,     0. , 32004.5, ...,     0. ,     0. ,     0. ],
       ...,
       [    0. ,     0. ,     0. , ..., 32004.5,     0. ,     0. ],
       [    0. ,     0. ,     0. , ...,     0. , 32258. ,     0. ],
       [    0. ,     0. ,     0. , ...,     0. ,     0. , 32512.5]])

In [23]:
lhs = kin_mat + vext_mat

In [24]:
lhs

array([[32748.73+0.j,   -70.28+0.j,   -50.  +0.j, ...,     0.  +0.j,     0.  +0.j,     0.  +0.j],
       [  -70.28+0.j, 32494.23+0.j,   -70.28+0.j, ...,     0.  +0.j,     0.  +0.j,     0.  +0.j],
       [  -50.  +0.j,   -70.28+0.j, 32240.73+0.j, ...,     0.  +0.j,     0.  +0.j,     0.  +0.j],
       ...,
       [    0.  +0.j,     0.  +0.j,     0.  +0.j, ..., 32240.73+0.j,   -70.28+0.j,   -50.  +0.j],
       [    0.  +0.j,     0.  +0.j,     0.  +0.j, ...,   -70.28+0.j, 32494.23+0.j,   -70.28+0.j],
       [    0.  +0.j,     0.  +0.j,     0.  +0.j, ...,   -50.  +0.j,   -70.28+0.j, 32748.73+0.j]])

In [25]:
e, v = np.linalg.eigh(lhs)

In [26]:
e

array([1.84e+00, 7.35e+00, 1.65e+01, 2.93e+01, 4.58e+01, 6.59e+01, 8.96e+01, 1.17e+02, 1.47e+02, 1.81e+02, 2.18e+02, 2.58e+02, 2.99e+02, 3.14e+02, 3.15e+02, 3.16e+02, 3.18e+02, 3.20e+02, 3.22e+02,
       3.25e+02, 3.27e+02, 3.32e+02, 3.34e+02, 3.41e+02, 3.42e+02, 3.50e+02, 3.51e+02, 3.60e+02, 3.63e+02, 3.72e+02, 3.76e+02, 3.87e+02, 3.89e+02, 4.01e+02, 4.02e+02, 4.16e+02, 4.19e+02, 4.33e+02,
       4.37e+02, 4.53e+02, 4.54e+02, 4.71e+02, 4.73e+02, 4.91e+02, 4.94e+02, 5.14e+02, 5.15e+02, 5.36e+02, 5.38e+02, 5.59e+02, 5.62e+02, 5.85e+02, 5.86e+02, 6.10e+02, 6.12e+02, 6.37e+02, 6.39e+02,
       6.65e+02, 6.66e+02, 6.94e+02, 6.96e+02, 7.25e+02, 7.26e+02, 7.55e+02, 7.57e+02, 7.87e+02, 7.89e+02, 8.21e+02, 8.22e+02, 8.54e+02, 8.57e+02, 8.90e+02, 8.91e+02, 9.26e+02, 9.28e+02, 9.63e+02,
       9.65e+02, 1.00e+03, 1.00e+03, 1.04e+03, 1.04e+03, 1.08e+03, 1.08e+03, 1.12e+03, 1.12e+03, 1.17e+03, 1.17e+03, 1.21e+03, 1.21e+03, 1.25e+03, 1.25e+03, 1.30e+03, 1.30e+03, 1.34e+03, 1.35e+03,
       1.39e+03

In [27]:
(e/e[0])**0.5

array([  1.  ,   2.  ,   3.  ,   4.  ,   4.99,   5.99,   6.98,   7.97,   8.96,   9.94,  10.91,  11.86,  12.77,  13.08,  13.1 ,  13.12,  13.15,  13.2 ,  13.24,  13.31,  13.35,  13.45,  13.49,  13.62,
        13.63,  13.8 ,  13.83,  14.  ,  14.06,  14.24,  14.3 ,  14.51,  14.55,  14.78,  14.8 ,  15.05,  15.11,  15.36,  15.42,  15.7 ,  15.71,  16.01,  16.05,  16.35,  16.41,  16.73,  16.74,  17.08,
        17.11,  17.45,  17.49,  17.85,  17.85,  18.22,  18.26,  18.62,  18.66,  19.03,  19.05,  19.43,  19.47,  19.86,  19.87,  20.27,  20.3 ,  20.7 ,  20.73,  21.14,  21.15,  21.56,  21.6 ,  22.02,
        22.02,  22.45,  22.47,  22.9 ,  22.92,  23.35,  23.37,  23.8 ,  23.82,  24.26,  24.27,  24.71,  24.74,  25.18,  25.19,  25.64,  25.66,  26.11,  26.12,  26.58,  26.59,  27.05,  27.06,  27.52,
        27.53,  27.99,  28.01,  28.47,  28.48,  28.95,  28.96,  29.43,  29.43,  29.91,  29.92,  30.39,  30.4 ,  30.87,  30.89,  31.36,  31.37,  31.84,  31.86,  32.33,  32.34,  32.82,  32.83,  33.31,
     

In [28]:
v

array([[-3.04e-06+0.j,  1.47e-05+0.j, -5.16e-06+0.j, ...,  1.45e-01+0.j, -6.87e-01+0.j,  6.87e-01+0.j],
       [-7.37e-06+0.j,  9.63e-06+0.j, -1.50e-05+0.j, ...,  6.63e-01+0.j,  1.63e-01+0.j, -1.63e-01+0.j],
       [-9.28e-06+0.j,  7.38e-07+0.j, -1.89e-05+0.j, ..., -1.92e-01+0.j,  4.31e-02+0.j, -4.31e-02+0.j],
       ...,
       [-9.28e-06+0.j, -7.38e-07+0.j, -1.89e-05+0.j, ..., -1.92e-01+0.j, -4.31e-02+0.j, -4.31e-02+0.j],
       [-7.37e-06+0.j, -9.63e-06+0.j, -1.50e-05+0.j, ...,  6.63e-01+0.j, -1.63e-01+0.j, -1.63e-01+0.j],
       [-3.04e-06+0.j, -1.47e-05+0.j, -5.16e-06+0.j, ...,  1.45e-01+0.j,  6.87e-01+0.j,  6.87e-01+0.j]])

In [29]:
w1 = np.zeros(vext.shape[0], dtype=np.complex128)

In [30]:
w1

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
     

In [31]:
tuple(basis_nwn.T)

(array([-255, -254, -253, -252, -251, -250, -249, -248, -247, -246, -245, -244, -243, -242, -241, -240, -239, -238, -237, -236, -235, -234, -233, -232, -231, -230, -229, -228, -227, -226, -225, -224,
        -223, -222, -221, -220, -219, -218, -217, -216, -215, -214, -213, -212, -211, -210, -209, -208, -207, -206, -205, -204, -203, -202, -201, -200, -199, -198, -197, -196, -195, -194, -193, -192,
        -191, -190, -189, -188, -187, -186, -185, -184, -183, -182, -181, -180, -179, -178, -177, -176, -175, -174, -173, -172, -171, -170, -169, -168, -167, -166, -165, -164, -163, -162, -161, -160,
        -159, -158, -157, -156, -155, -154, -153, -152, -151, -150, -149, -148, -147, -146, -145, -144, -143, -142, -141, -140, -139, -138, -137, -136, -135, -134, -133, -132, -131, -130, -129, -128,
        -127, -126, -125, -124, -123, -122, -121, -120, -119, -118, -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107, -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,


In [32]:
w1[tuple(basis_nwn.T)] = v[:,0]

In [33]:
w1

array([-4.61e-01+0.j, -4.32e-01+0.j, -3.53e-01+0.j, -2.45e-01+0.j, -1.34e-01+0.j, -4.51e-02+0.j,  1.02e-02+0.j,  3.06e-02+0.j,  2.58e-02+0.j,  9.75e-03+0.j, -5.18e-03+0.j, -1.20e-02+0.j,
       -1.01e-02+0.j, -3.39e-03+0.j,  3.20e-03+0.j,  6.21e-03+0.j,  5.03e-03+0.j,  1.39e-03+0.j, -2.13e-03+0.j, -3.67e-03+0.j, -2.84e-03+0.j, -6.17e-04+0.j,  1.49e-03+0.j,  2.34e-03+0.j,
        1.74e-03+0.j,  2.81e-04+0.j, -1.07e-03+0.j, -1.58e-03+0.j, -1.13e-03+0.j, -1.26e-04+0.j,  7.85e-04+0.j,  1.11e-03+0.j,  7.73e-04+0.j,  5.24e-05+0.j, -5.91e-04+0.j, -8.12e-04+0.j,
       -5.49e-04+0.j, -1.71e-05+0.j,  4.53e-04+0.j,  6.08e-04+0.j,  4.04e-04+0.j,  5.95e-07+0.j, -3.53e-04+0.j, -4.67e-04+0.j, -3.06e-04+0.j,  6.60e-06+0.j,  2.80e-04+0.j,  3.66e-04+0.j,
        2.38e-04+0.j, -9.13e-06+0.j, -2.25e-04+0.j, -2.92e-04+0.j, -1.89e-04+0.j,  9.36e-06+0.j,  1.82e-04+0.j,  2.36e-04+0.j,  1.53e-04+0.j, -8.51e-06+0.j, -1.50e-04+0.j, -1.94e-04+0.j,
       -1.26e-04+0.j,  7.22e-06+0.j,  1.24e-04+0.j,  1.61e-04+0.j

In [34]:
w = np.zeros((basis_nwn.shape[0], vext.shape[0]), dtype=np.complex128)

In [35]:
w[(slice(None), ) + tuple(basis_nwn.T)] = v.T

In [36]:
w

array([[-4.61e-01+0.j, -4.32e-01+0.j, -3.53e-01+0.j, ..., -2.45e-01+0.j, -3.53e-01+0.j, -4.32e-01+0.j],
       [-7.38e-14+0.j, -1.82e-01+0.j, -3.18e-01+0.j, ...,  3.76e-01+0.j,  3.18e-01+0.j,  1.82e-01+0.j],
       [-1.57e-01+0.j, -1.11e-01+0.j,  1.25e-02+0.j, ...,  1.67e-01+0.j,  1.25e-02+0.j, -1.11e-01+0.j],
       ...,
       [ 1.24e-05+0.j,  7.44e-06+0.j, -8.11e-06+0.j, ..., -1.58e-05+0.j, -8.11e-06+0.j,  7.44e-06+0.j],
       [ 9.62e-13+0.j, -2.73e-07+0.j, -1.92e-06+0.j, ...,  9.35e-06+0.j,  1.92e-06+0.j,  2.73e-07+0.j],
       [ 2.01e-05+0.j,  7.81e-06+0.j, -7.44e-06+0.j, ..., -1.15e-05+0.j, -7.44e-06+0.j,  7.81e-06+0.j]])

In [37]:
w_re = np.fft.ifft(w)

In [38]:
w_re

array([[-5.41e-03+0.00e+00j, -5.41e-03+4.88e-17j, -5.40e-03+1.01e-16j, ..., -5.39e-03-1.52e-16j, -5.40e-03-1.01e-16j, -5.41e-03-4.87e-17j],
       [-1.69e-16+0.00e+00j, -1.68e-16-2.54e-04j, -1.81e-16-5.08e-04j, ..., -1.89e-16+7.60e-04j, -1.81e-16+5.08e-04j, -1.68e-16+2.54e-04j],
       [ 5.40e-03+0.00e+00j,  5.39e-03+1.33e-17j,  5.35e-03+3.36e-17j, ...,  5.28e-03-5.23e-17j,  5.35e-03-3.37e-17j,  5.39e-03-1.33e-17j],
       ...,
       [ 2.28e-03+0.00e+00j, -2.28e-03+1.04e-12j,  2.28e-03-2.09e-12j, ..., -2.28e-03-3.13e-12j,  2.28e-03+2.09e-12j, -2.28e-03-1.04e-12j],
       [ 9.13e-11+0.00e+00j, -9.13e-11+1.36e-05j,  9.14e-11-2.72e-05j, ..., -9.14e-11-4.09e-05j,  9.14e-11+2.72e-05j, -9.13e-11-1.36e-05j],
       [ 1.91e-03+0.00e+00j, -1.91e-03-6.52e-13j,  1.91e-03+1.30e-12j, ..., -1.91e-03+1.96e-12j,  1.91e-03-1.30e-12j, -1.91e-03+6.52e-13j]])

In [39]:
np.abs(w_re)

array([[5.41e-03, 5.41e-03, 5.40e-03, ..., 5.39e-03, 5.40e-03, 5.41e-03],
       [1.69e-16, 2.54e-04, 5.08e-04, ..., 7.60e-04, 5.08e-04, 2.54e-04],
       [5.40e-03, 5.39e-03, 5.35e-03, ..., 5.28e-03, 5.35e-03, 5.39e-03],
       ...,
       [2.28e-03, 2.28e-03, 2.28e-03, ..., 2.28e-03, 2.28e-03, 2.28e-03],
       [9.13e-11, 1.36e-05, 2.72e-05, ..., 4.09e-05, 2.72e-05, 1.36e-05],
       [1.91e-03, 1.91e-03, 1.91e-03, ..., 1.91e-03, 1.91e-03, 1.91e-03]])